// Generated by LiveScript 1.2.0
(function(){
  var ExhibitionController;
  this.ExhibitionController = ExhibitionController = function($scope, $rootScope, $filter){
    var noMoreKonograms;
    noMoreKonograms = false;
    $scope.konograms = [];
    $scope.promotionDate = function(promotionObj){
      var dateFilter, dateFormat;
      dateFilter = $filter('date');
      dateFormat = 'yyyy-MM-dd HH:mm:ss';
      if (promotionObj === null) {
        return 'N/A';
      } else if (promotionObj.from === 0 && promotionObj.to !== 2147483647) {
        return '???? - ' + dateFilter(promotionObj.to * 1000, dateFormat);
      } else if (promotionObj.from !== 0 && promotionObj.to === 2147483647) {
        return dateFilter(promotionObj.from * 1000, dateFormat) + ' - ????';
      } else {
        return dateFilter(promotionObj.from * 1000, dateFormat) + ' - ' + dateFilter(promotionObj.to * 1000, dateFormat);
      }
    };
    $scope.$on('clear', function(e){
      console.log('receive clear event');
      $scope.konograms = [];
    });
    $scope.$on('newKonograms', function(e, newKonograms){
      noMoreKonograms = newKonograms.length === 0;
      angular.forEach(newKonograms, function(konogram){
        return $scope.konograms.push(konogram);
      });
    });
    $scope.loadMore = function(){
      var numKonograms, lastKonogramID;
      if (noMoreKonograms) {
        return;
      }
      console.log('loadMore');
      numKonograms = $scope.konograms.length;
      lastKonogramID = numKonograms > 0 ? $scope.konograms[numKonograms - 1].id : null;
      $rootScope.$broadcast('loadMore', lastKonogramID);
    };
  };
  ExhibitionController.$inject = ['$scope', '$rootScope', '$filter'];
}).call(this);
