// Generated by LiveScript 1.2.0
(function(){
  var ExhibitionController;
  this.ExhibitionController = ExhibitionController = function($scope, $rootScope){
    var noMoreKonograms;
    noMoreKonograms = false;
    $scope.konograms = [];
    $scope.promotionDate = function(promotionObj){
      if (promotionObj === null) {
        return 'N/A';
      }
    };
    $scope.$on('clear', function(e){
      console.log('receive clear event');
      $scope.konograms = [];
    });
    $scope.$on('newKonograms', function(e, newKonograms){
      noMoreKonograms = newKonograms.length === 0;
      angular.forEach(newKonograms, function(konogram){
        return $scope.konograms.push(konogram);
      });
    });
    $scope.loadMore = function(){
      var numKonograms, lastKonogramID;
      if (noMoreKonograms) {
        return;
      }
      console.log('loadMore');
      numKonograms = $scope.konograms.length;
      lastKonogramID = numKonograms > 0 ? $scope.konograms[numKonograms - 1].id : null;
      $rootScope.$broadcast('loadMore', lastKonogramID);
    };
  };
  ExhibitionController.$inject = ['$scope', '$rootScope'];
}).call(this);
