// Generated by LiveScript 1.2.0
(function(){
  var NavbarController;
  this.NavbarController = NavbarController = function($scope, $rootScope){
    var env;
    env = null;
    $scope.setEnv = function(e){
      env = e;
      console.log('emit clear event');
      $rootScope.$broadcast('clear');
      console.log('emit envChanged event');
      $rootScope.$broadcast('envChanged', e);
    };
    $scope.getEnv = function(){
      return env;
    };
    $scope.setEnv('development');
  };
  NavbarController.$inject = ['$scope', '$rootScope'];
}).call(this);
