// Generated by LiveScript 1.2.0
(function(){
  var NavbarController;
  NavbarController = function($scope, $rootScope){
    var env;
    env = null;
    $scope.setEnv = function(e){
      env = e;
      $rootScope.$broadcast('envChanged', e);
      console.log('emit envChanged event');
    };
    $scope.getEnv = function(){
      return env;
    };
    $scope.setEnv('development');
  };
  NavbarController.$inject = ['$scope', '$rootScope'];
  this.NavbarController = NavbarController;
}).call(this);
