// Generated by LiveScript 1.2.0
(function(){
  var SearchController;
  this.SearchController = SearchController = function($scope, $rootScope, $http){
    var API, endpoint, onEnvChanged, beforeQuery, afterQuery, success, error;
    API = {
      development: 'http://127.0.0.1/KonoServer/konograms',
      production: 'http://yteam.thekono.com/KPI2/konograms'
    };
    endpoint = API['development'];
    $scope.kid = '';
    $scope.dateSince = null;
    $scope.dateUntil = null;
    $scope.chronological = false;
    $scope.waitingResponse = false;
    onEnvChanged = function(e, env){
      endpoint = API[env];
      console.log('receive envChanged event');
      return $scope.queryKonograms();
    };
    $scope.clear = function(){
      return $rootScope.$broadcast('clear');
    };
    $scope.queryKonograms = function(konogramID){
      var data, t;
      konogramID == null && (konogramID = null);
      if ($scope.waitingResponse) {
        return;
      }
      data = {
        callback: 'JSON_CALLBACK',
        promotion: 1
      };
      if ($scope.kid !== '') {
        data.kid = $scope.kid;
      }
      t = new Date($scope.dateSince).getTime() / 1000;
      if (!isNaN(t) && t > 0) {
        data.from = t;
      }
      t = new Date($scope.dateUntil).getTime() / 1000;
      if (!isNaN(t) && t > 0) {
        data.to = t;
      }
      if (!$scope.chronological) {
        data.reverse = 1;
      }
      if (konogramID !== null) {
        data[$scope.chronological ? 'after' : 'before'] = konogramID;
      }
      beforeQuery();
      return $http.jsonp(endpoint, {
        params: data
      }).success(success).error(error);
    };
    beforeQuery = function(){
      return $scope.waitingResponse = true;
    };
    afterQuery = function(){
      return $scope.waitingResponse = false;
    };
    success = function(data){
      afterQuery();
      return $rootScope.$broadcast('newKonograms', data);
    };
    error = function(data){
      return afterQuery();
    };
    $scope.$on('envChanged', onEnvChanged);
    $scope.$on('loadMore', function(e, konogramID){
      $scope.queryKonograms(konogramID);
    });
  };
  SearchController.$inject = ['$scope', '$rootScope', '$http'];
}).call(this);
