// Generated by LiveScript 1.2.0
(function(){
  var SearchController;
  SearchController = function($scope, $rootScope, $http){
    var API, endpoint, onEnvChanged, queryKonograms;
    API = {
      development: 'http://127.0.0.1/KonoServer/konograms',
      production: 'http://yteam.thekono.com/KPI2/konograms'
    };
    endpoint = null;
    $scope.kid = '';
    $scope.dateSince = null;
    $scope.dateUntil = null;
    onEnvChanged = function(e, env){
      endpoint = API[env];
      return queryKonograms();
    };
    queryKonograms = function(){
      var data, t;
      data = {};
      if ($scope.kid !== '') {
        data.kid = $scope.kid;
      }
      t = new Date($scope.dateSince).getTime() / 1000;
      if (!isNaN(t)) {
        data.from = t;
      }
      t = new Date($scope.dateUntil).getTime() / 1000;
      if (!isNaN(t)) {
        data.to = t;
      }
      return $http.get(endpoint, {
        params: data
      });
    };
    $scope.$on('envChanged', onEnvChanged);
  };
  SearchController.$inject = ['$scope', '$rootScope', '$http'];
  this.SearchController = SearchController;
}).call(this);
